package com.edusys.ui;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import com.edusys.utils.DialogHelper;
import com.edusys.entity.ShareHelper;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Đăng Ngô
 */
public class Polypro extends javax.swing.JFrame implements Runnable {

    quanlynguoihoc qlnh = new quanlynguoihoc();
    Quanlychuyende qlcd = new Quanlychuyende();
    Quanlinhanvienquantri qlnv = new Quanlinhanvienquantri();
    Quanlykhoahoc qlkh = new Quanlykhoahoc();

    @Override
    public void run() {
        while (true) {
            try {
                Date now = new Date();
                SimpleDateFormat formater = new SimpleDateFormat();
                formater.applyPattern("hh:mm:ss aa");
                String time = formater.format(now);
                Thread.sleep(1000);
                txtdongho.setText(time);
            } catch (InterruptedException ex) {
                break;
            }
        }
    }

    /**
     * Creates new form Polypro
     */
    public Polypro() {
        ChaoJDialog s = new ChaoJDialog(this, true);
        s.setVisible(true);
        new Dangnhap(this, true).setVisible(true);
        initComponents();
        setLocationRelativeTo(null);
    }

    void openLogin() {
        Dangnhap dn = new Dangnhap(this, true);
        dn.setVisible(true);
    }

    void logoff() {
        ShareHelper.logoff();
        this.openLogin();
    }

    void exit() {
        if (DialogHelper.confirm(this, "bạn thực sự muốn kết thúc")) {
            System.exit(0);
        }
    }

    void openThongke(int index) {
        if (ShareHelper.authenticated()) {
            Tonghopthongke s = new Tonghopthongke();
            s.setVisible(true);
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập!");
        }
    }

    void openNhanvien() {
        if (ShareHelper.authenticated()) {
            new Quanlinhanvienquantri().setVisible(true);
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập!");
        }
    }

    void openKhoahoc() {
        if (ShareHelper.authenticated()) {
            new Quanlykhoahoc().setVisible(true);
        } else {
            DialogHelper.alert(this, "vui lòng đăng nhập");
        }
    }

    void openChuyende() {
        if (ShareHelper.authenticated()) {
            new Quanlychuyende().setVisible(true);
        } else {
            DialogHelper.alert(this, "vui lòng đăng nhập");
        }
    }

    void openNguoihoc() {
        if (ShareHelper.authenticated()) {
            new quanlynguoihoc().setVisible(true);
        } else {
            DialogHelper.alert(this, "vui lòng đăng nhập");
        }
    }

    void openWebsite() {
        try {
            Desktop.getDesktop().browse(new File("index.html").toURI());
        } catch (IOException ex) {
            DialogHelper.alert(this, "Không tìm thấy file hướng dẫn!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnDangXuat = new javax.swing.JButton();
        btnKetThuc = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnChuyenDe = new javax.swing.JButton();
        btnNguoiHoc = new javax.swing.JButton();
        btnKhoaHoc = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtdongho = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnDangNhap = new javax.swing.JMenuItem();
        jbtnDangXuat = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jbtnDoimk = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jbtnKetThuc = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jbtnNguoiHoc = new javax.swing.JMenuItem();
        jbtnKhoaHoc = new javax.swing.JMenuItem();
        jbtnChuyenDe = new javax.swing.JMenuItem();
        jbtnNhanVien = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jbtnNguoiHocTungNam = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jbtnBangDiem = new javax.swing.JMenuItem();
        jbtnDiemtungKhoaHoc = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jtbnTongHop = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jbtnHuongDan = new javax.swing.JMenuItem();
        jbtnGioiThieu = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HỆ THỐNG QUẢN LÝ ĐÀO TẠO");

        jToolBar1.setRollover(true);

        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/Exit.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDangXuat);

        btnKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/Stop sign.png"))); // NOI18N
        btnKetThuc.setText("Kết thúc");
        btnKetThuc.setFocusable(false);
        btnKetThuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKetThuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetThucActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKetThuc);
        jToolBar1.add(jSeparator6);

        btnChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/List.png"))); // NOI18N
        btnChuyenDe.setText("Chuyên đề");
        btnChuyenDe.setFocusable(false);
        btnChuyenDe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChuyenDe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenDeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnChuyenDe);

        btnNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/People.png"))); // NOI18N
        btnNguoiHoc.setText("Người học");
        btnNguoiHoc.setFocusable(false);
        btnNguoiHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNguoiHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNguoiHocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNguoiHoc);

        btnKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/Bee.png"))); // NOI18N
        btnKhoaHoc.setText("Khóa học");
        btnKhoaHoc.setFocusable(false);
        btnKhoaHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhoaHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaHocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKhoaHoc);

        jSeparator7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jToolBar1.add(jSeparator7);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/Earth.png"))); // NOI18N
        jButton6.setText("Hướng dẫn");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/images/cropped-cropped-logo-fpt.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/Info.png"))); // NOI18N
        jLabel2.setText("Hệ thống quản lí đàn tạo");

        txtdongho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/Alarm.png"))); // NOI18N
        txtdongho.setText("Times");
        txtdongho.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtdonghoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtdongho, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator5)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtdongho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jMenu1.setText("Hệ Thống");

        btnDangNhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        btnDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/Blue key.png"))); // NOI18N
        btnDangNhap.setText("Đăng Nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        jMenu1.add(btnDangNhap);

        jbtnDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jbtnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/Exit.png"))); // NOI18N
        jbtnDangXuat.setText("Đăng Xuất");
        jbtnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(jbtnDangXuat);
        jMenu1.add(jSeparator1);

        jbtnDoimk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/Sync.png"))); // NOI18N
        jbtnDoimk.setText("Đổi mật khẩu");
        jbtnDoimk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDoimkActionPerformed(evt);
            }
        });
        jMenu1.add(jbtnDoimk);
        jMenu1.add(jSeparator2);

        jbtnKetThuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        jbtnKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/Stop sign.png"))); // NOI18N
        jbtnKetThuc.setText("Kết thúc");
        jbtnKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKetThucActionPerformed(evt);
            }
        });
        jMenu1.add(jbtnKetThuc);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản Lý");

        jbtnNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/People.png"))); // NOI18N
        jbtnNguoiHoc.setText("Người học");
        jbtnNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNguoiHocActionPerformed(evt);
            }
        });
        jMenu2.add(jbtnNguoiHoc);

        jbtnKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/Bee.png"))); // NOI18N
        jbtnKhoaHoc.setText("Khóa học");
        jbtnKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKhoaHocActionPerformed(evt);
            }
        });
        jMenu2.add(jbtnKhoaHoc);

        jbtnChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/List.png"))); // NOI18N
        jbtnChuyenDe.setText("Chuyên đề");
        jbtnChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChuyenDeActionPerformed(evt);
            }
        });
        jMenu2.add(jbtnChuyenDe);

        jbtnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/User group.png"))); // NOI18N
        jbtnNhanVien.setText("Nhân viên");
        jbtnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNhanVienActionPerformed(evt);
            }
        });
        jMenu2.add(jbtnNhanVien);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Thống kê");

        jbtnNguoiHocTungNam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/Female.png"))); // NOI18N
        jbtnNguoiHocTungNam.setText("Người học từng năm");
        jbtnNguoiHocTungNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNguoiHocTungNamActionPerformed(evt);
            }
        });
        jMenu3.add(jbtnNguoiHocTungNam);
        jMenu3.add(jSeparator3);

        jbtnBangDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/Text.png"))); // NOI18N
        jbtnBangDiem.setText("Bảng điểm khóa");
        jbtnBangDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBangDiemActionPerformed(evt);
            }
        });
        jMenu3.add(jbtnBangDiem);

        jbtnDiemtungKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/3d bar chart.png"))); // NOI18N
        jbtnDiemtungKhoaHoc.setText("Điểm từng khóa học");
        jbtnDiemtungKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDiemtungKhoaHocActionPerformed(evt);
            }
        });
        jMenu3.add(jbtnDiemtungKhoaHoc);
        jMenu3.add(jSeparator4);

        jtbnTongHop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/User group.png"))); // NOI18N
        jtbnTongHop.setText("Tổng Hợp - Thống Kê");
        jtbnTongHop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnTongHopActionPerformed(evt);
            }
        });
        jMenu3.add(jtbnTongHop);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Trợ Giúp");

        jbtnHuongDan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jbtnHuongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/Earth.png"))); // NOI18N
        jbtnHuongDan.setText("Hướng dẫn sử dụng");
        jMenu5.add(jbtnHuongDan);

        jbtnGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/Home.png"))); // NOI18N
        jbtnGioiThieu.setText("Giới thiệu phần mềm");
        jbtnGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGioiThieuActionPerformed(evt);
            }
        });
        jMenu5.add(jbtnGioiThieu);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        this.openLogin();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void jbtnKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKetThucActionPerformed
        // TODO add your handling code here:
        this.exit();
    }//GEN-LAST:event_jbtnKetThucActionPerformed

    private void jbtnNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNguoiHocActionPerformed
        // TODO add your handling code here:
        if (ShareHelper.USER.isVaiTro()) {
            this.openNguoihoc();
        }
    }//GEN-LAST:event_jbtnNguoiHocActionPerformed

    private void jbtnChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChuyenDeActionPerformed
        // TODO add your handling code here:
        if (ShareHelper.USER.isVaiTro()) {
            if (!qlcd.isActive()) {
                qlcd.setVisible(true);
            }
        }
    }//GEN-LAST:event_jbtnChuyenDeActionPerformed

    private void jbtnBangDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBangDiemActionPerformed
        // TODO add your handling code here:
        Tonghopthongke.tabIndex = 1;
        this.openThongke(WIDTH);
    }//GEN-LAST:event_jbtnBangDiemActionPerformed

    private void btnChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenDeActionPerformed

        if (ShareHelper.USER.isVaiTro()) {
            if (!qlcd.isActive()) {
                qlcd.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnChuyenDeActionPerformed

    private void txtdonghoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtdonghoAncestorAdded
        // TODO add your handling code here:
        Thread t = new Thread(this);
        t.start();
    }//GEN-LAST:event_txtdonghoAncestorAdded

    private void jbtnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNhanVienActionPerformed
        // TODO add your handling code here:
        if (ShareHelper.USER.isVaiTro()) {
            if (!qlnv.isActive()) {
                qlnv.setVisible(true);
            }
        }
    }//GEN-LAST:event_jbtnNhanVienActionPerformed

    private void jbtnKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKhoaHocActionPerformed
        // TODO add your handling code here:
        if (ShareHelper.USER.isVaiTro()) {
            if (!qlkh.isActive()) {
                qlkh.setVisible(true);
            }
        }
    }//GEN-LAST:event_jbtnKhoaHocActionPerformed

    private void jbtnNguoiHocTungNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNguoiHocTungNamActionPerformed
        // TODO add your handling code here:
        Tonghopthongke.tabIndex = 0;
        this.openThongke(WIDTH);
    }//GEN-LAST:event_jbtnNguoiHocTungNamActionPerformed

    private void jbtnDiemtungKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDiemtungKhoaHocActionPerformed
        // TODO add your handling code here:
        Tonghopthongke.tabIndex = 2;
        this.openThongke(WIDTH);
    }//GEN-LAST:event_jbtnDiemtungKhoaHocActionPerformed

    private void jtbnTongHopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnTongHopActionPerformed
        Tonghopthongke.tabIndex = 3;
        this.openThongke(WIDTH);
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbnTongHopActionPerformed

    private void jbtnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDangXuatActionPerformed
        // TODO add your handling code here:
        this.logoff();
    }//GEN-LAST:event_jbtnDangXuatActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        this.logoff();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetThucActionPerformed
        // TODO add your handling code here:
        this.exit();
    }//GEN-LAST:event_btnKetThucActionPerformed

    private void btnKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaHocActionPerformed
        // TODO add your handling code here:
        if (ShareHelper.USER.isVaiTro()) {
            new Quanlykhoahoc().setVisible(true);
        }
    }//GEN-LAST:event_btnKhoaHocActionPerformed

    private void btnNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNguoiHocActionPerformed
        // TODO add your handling code here:
        if (ShareHelper.USER.isVaiTro()) {
            new quanlynguoihoc().setVisible(true);
        }
    }//GEN-LAST:event_btnNguoiHocActionPerformed

    private void jbtnGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGioiThieuActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jbtnGioiThieuActionPerformed

    private void jbtnDoimkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDoimkActionPerformed
        // TODO add your handling code here:
        new ChangePass().setVisible(true);
    }//GEN-LAST:event_jbtnDoimkActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Polypro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Polypro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Polypro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Polypro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Polypro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChuyenDe;
    private javax.swing.JMenuItem btnDangNhap;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnKetThuc;
    private javax.swing.JButton btnKhoaHoc;
    private javax.swing.JButton btnNguoiHoc;
    private javax.swing.JButton jButton6;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem jbtnBangDiem;
    private javax.swing.JMenuItem jbtnChuyenDe;
    private javax.swing.JMenuItem jbtnDangXuat;
    private javax.swing.JMenuItem jbtnDiemtungKhoaHoc;
    private javax.swing.JMenuItem jbtnDoimk;
    private javax.swing.JMenuItem jbtnGioiThieu;
    private javax.swing.JMenuItem jbtnHuongDan;
    private javax.swing.JMenuItem jbtnKetThuc;
    private javax.swing.JMenuItem jbtnKhoaHoc;
    private javax.swing.JMenuItem jbtnNguoiHoc;
    private javax.swing.JMenuItem jbtnNguoiHocTungNam;
    private javax.swing.JMenuItem jbtnNhanVien;
    private javax.swing.JMenuItem jtbnTongHop;
    private javax.swing.JLabel txtdongho;
    // End of variables declaration//GEN-END:variables

    private Object Tonghopthongke() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
